import { useState } from "react";
import {
  ArrowLeft,
  Printer,
  FileText,
  Download,
  Activity,
  User,
  CheckCircle2,
  Clock,
  Layers,
  Check,
  Building2,
  Mail,
  Phone,
  ExternalLink,
  Server,
  Database,
} from "lucide-react";
import { useAuditLogDetail, useMainAuditLogs } from "../hooks/useAuditLog";
import {
  SeverityBadgeLarge,
  StatusBadgeLarge,
} from "../components/AuditBadges";
import type { AuditCategory, AuditRecord } from "../types/auditlog.types";
import safehandshospital_logo from "../../../assets/safehandshospital_logo.webp";
import { useHospitalBranding } from "../../settings/hooks/useHospitalBranding";
import { useBillingConfiguration } from "../../billing/hooks/useBilling";

const PP = "Poppins, sans-serif";
const RB = "Roboto, sans-serif";

interface AuditLogDetailsPageProps {
  recordId: string;
  sourceCategory?: AuditCategory;
  onBack: () => void;
  onNavigateCategory?: (category: AuditCategory) => void;
}

function safeArray<T>(data: T[] | undefined | null): T[] {
  return Array.isArray(data) ? data : [];
}

function downloadAuditDetailCsv(record: AuditRecord, relatedLogs: AuditRecord[]): void {
  const sanitize = (val: unknown): string => {
    if (val === undefined || val === null) return "";
    let str = "";
    if (typeof val === "object") {
      try {
        str = JSON.stringify(val);
      } catch {
        str = String(val);
      }
    } else {
      str = String(val);
    }
    return `"${str.replace(/"/g, '""')}"`;
  };

  const rows: [string, string, unknown][] = [
    // Section 1: Audit Event Summary
    ["Audit Event Summary", "Audit ID", record.id],
    ["Audit Event Summary", "Event ID", record.id],
    ["Audit Event Summary", "Category", record.category],
    ["Audit Event Summary", "Module", record.module],
    ["Audit Event Summary", "Screen Name", `${record.module} Workspace`],
    ["Audit Event Summary", "Timestamp", record.timestamp],
    ["Audit Event Summary", "Generated By", record.user],
    ["Audit Event Summary", "Department", record.department || ""],
    ["Audit Event Summary", "User Role", record.userRole],
    ["Audit Event Summary", "Severity", record.severity],
    ["Audit Event Summary", "Status", record.status],
    ["Audit Event Summary", "Action Performed", record.action],
    ["Audit Event Summary", "Full Event Description", record.description],

    // Section 2: User Information
    ["User Information", "User Name", record.user],
    ["User Information", "User Role", record.userRole],
    ["User Information", "Department", record.department || ""],
    ["User Information", "User ID / Email", record.userId || ""],
    ["User Information", "Phone", ""],
    ["User Information", "Account Status", record.status],
    ["User Information", "Last Login", record.loginTime || ""],

    // Section 3: Activity Information
    ["Activity Information", "Action Performed", record.action],
    ["Activity Information", "Module", record.module],
    ["Activity Information", "Related Record ID", record.recordId || record.id],
    ["Activity Information", "IP Address", record.ipAddress || ""],
    ["Activity Information", "Device Type", record.device || ""],
    ["Activity Information", "Browser", record.browser || ""],
    ["Activity Information", "Auth Method", record.authenticationMethod || ""],
    ["Activity Information", "Session ID", record.sessionId || ""],
    ["Activity Information", "Network", record.metadata?.network ? String(record.metadata.network) : ""],

    // Section 4: Audit Timeline
    ["Audit Timeline", "Main Action", `${record.action} (${record.timestamp}) - ${record.description}`],
  ];

  if (record.changes && record.changes.length > 0) {
    record.changes.forEach((ch, idx) => {
      rows.push(["Audit Timeline", `Change #${idx + 1}`, `Changed ${ch.field}: ${ch.before} -> ${ch.after}`]);
    });
  }

  // Section 5: Data Comparison (if applicable)
  if (record.fieldChanged || record.oldValue || record.newValue) {
    rows.push(["Data Comparison", "Modified Field", record.fieldChanged || ""]);
    rows.push(["Data Comparison", "Previous Value (Before)", record.oldValue || ""]);
    rows.push(["Data Comparison", "Updated Value (After)", record.newValue || ""]);
  }

  // Section 6: Related Records
  rows.push(["Related Records", "Related Record ID", record.recordId || record.id]);
  rows.push(["Related Records", "Related Module", record.module]);

  // Section 7: Technical Information
  rows.push(["Technical Information", "IP Address", record.ipAddress || ""]);
  rows.push(["Technical Information", "Operating System", record.metadata?.operatingSystem ? String(record.metadata.operatingSystem) : ""]);
  rows.push(["Technical Information", "Device Type", record.device || ""]);
  rows.push(["Technical Information", "MAC Address", record.metadata?.macAddress ? String(record.metadata.macAddress) : ""]);
  rows.push(["Technical Information", "Hospital Branch", record.metadata?.branch ? String(record.metadata.branch) : ""]);
  rows.push(["Technical Information", "Session Duration", record.sessionDuration || ""]);
  rows.push(["Technical Information", "Login Method", record.authenticationMethod || ""]);
  rows.push(["Technical Information", "Timezone", record.metadata?.timezone ? String(record.metadata.timezone) : ""]);

  // Related Audit Events
  if (relatedLogs && relatedLogs.length > 0) {
    relatedLogs.forEach((log, idx) => {
      rows.push([
        "Related Audit Events",
        `Related Event #${idx + 1}`,
        `${log.timestamp} | ${log.module} | ${log.action} | By: ${log.user} | Severity: ${log.severity} | Status: ${log.status}`,
      ]);
    });
  }

  const csvContent =
    "\uFEFF" +
    "Section,Field,Value\n" +
    rows
      .map(
        ([s, f, v]) =>
          `${sanitize(s)},${sanitize(f)},${sanitize(v)}`,
      )
      .join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const filename = `Audit_Log_${record.id || "AUD-DETAIL"}.csv`;
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

export function AuditLogDetailsPage({
  recordId,
  sourceCategory = "All Logs",
  onBack,
}: AuditLogDetailsPageProps) {
  const { logoUrl } = useHospitalBranding();
  const { configuration } = useBillingConfiguration();
  const [logoLoaded, setLogoLoaded] = useState(true);

  const effectiveLogo = logoUrl || safehandshospital_logo;
  const hospitalName =
    configuration?.receipt?.hospitalName || "Safe Hands Hospital";
  const hospitalAddress =
    configuration?.receipt?.hospitalAddress ||
    "123 Healthcare Ave, Medical District, City";
  const hospitalPhone =
    configuration?.receipt?.hospitalPhone || "+91 98765 43210";
  const hospitalEmail =
    configuration?.receipt?.hospitalEmail || "info@safehandshospital.com";
  const hospitalGstin = configuration?.receipt?.hospitalGstin || "";

  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const {
    data: record,
    isLoading,
    isError,
  } = useAuditLogDetail(recordId, sourceCategory);
  const { data: relatedData } = useMainAuditLogs({ page: 0, size: 10 });

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  const handlePrint = () => {
    const originalTitle = document.title;
    document.title = `Audit_Detail_${record?.id || "AUD-REPORT"}`;
    window.print();
    setTimeout(() => {
      document.title = originalTitle;
    }, 1000);
  };

  const handleExportPdf = () => {
    const originalTitle = document.title;
    document.title = `Audit_Log_${record?.id || "AUD-REPORT"}`;
    window.print();
    setTimeout(() => {
      document.title = originalTitle;
    }, 1000);
  };

  const relatedAuditLogs = safeArray(relatedData?.content);

  if (isLoading) {
    return (
      <div
        className="flex-1 overflow-y-auto p-6 space-y-6 bg-[#F1F5F9]"
        style={{ fontFamily: RB }}
      >
        <div className="py-16 text-center space-y-4">
          <div className="w-16 h-16 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center mx-auto animate-spin">
            <Clock className="w-8 h-8" />
          </div>
          <div>
            <h3
              className="text-base font-bold text-gray-800"
              style={{ fontFamily: PP }}
            >
              Loading Audit Log Details...
            </h3>
            <p className="text-xs text-gray-500 mt-1">
              Fetching audit record {recordId}.
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (isError || !record) {
    return (
      <div
        className="flex-1 overflow-y-auto p-6 space-y-6 bg-[#F1F5F9]"
        style={{ fontFamily: RB }}
      >
        <div className="py-16 text-center space-y-4">
          <div className="w-16 h-16 bg-red-100 text-red-600 rounded-full flex items-center justify-center mx-auto">
            <Database className="w-8 h-8" />
          </div>
          <div>
            <h3
              className="text-base font-bold text-gray-800"
              style={{ fontFamily: PP }}
            >
              Audit Record Not Found
            </h3>
            <p className="text-xs text-gray-500 mt-1">
              {isError
                ? `Failed to load audit record ${recordId}. The server encountered an internal error.`
                : `The audit record ${recordId} could not be found.`}
            </p>
          </div>
          <button
            onClick={onBack}
            className="inline-flex items-center gap-2 px-4 py-2 text-xs font-semibold text-white rounded-lg"
            style={{ backgroundColor: "#0D47A1" }}
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Audit Logs
          </button>
        </div>
      </div>
    );
  }

  return (
    <>
      {/* ─── PRINT-SPECIFIC CSS ─── */}
      <style>{`
        @page {
          size: A4 portrait;
          margin: 10mm;
        }
        @media screen {
          .audit-detail-print-only {
            display: none !important;
          }
        }
        @media print {
          html, body {
            background: #ffffff !important;
            margin: 0 !important;
            padding: 0 !important;
            overflow: visible !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          /* Hide application shell, navbar, sidebar, buttons, and normal screen UI */
          .audit-detail-screen-ui,
          nav,
          aside,
          header,
          footer,
          button,
          .no-print {
            display: none !important;
          }
          /* Show dedicated print document */
          .audit-detail-print-only {
            display: block !important;
            position: absolute !important;
            left: 0 !important;
            top: 0 !important;
            width: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
            background: #ffffff !important;
            color: #000000 !important;
            font-size: 8.5pt !important;
            line-height: 1.35 !important;
            overflow: visible !important;
          }
          .audit-detail-print-only table {
            width: 100% !important;
            border-collapse: collapse !important;
            margin-top: 4px !important;
          }
          .audit-detail-print-only thead {
            display: table-header-group !important;
          }
          .audit-detail-print-only tbody {
            display: table-row-group !important;
          }
          .audit-detail-print-only tr {
            break-inside: avoid !important;
            page-break-inside: avoid !important;
          }
          .audit-detail-print-only th,
          .audit-detail-print-only td {
            border: 1px solid #cbd5e1 !important;
            padding: 3px 5px !important;
            font-size: 8pt !important;
            vertical-align: top !important;
            white-space: normal !important;
            overflow-wrap: anywhere !important;
            word-break: break-word !important;
          }
          .audit-detail-print-only th {
            background-color: #f1f5f9 !important;
            color: #0f172a !important;
            font-weight: 700 !important;
            text-align: left !important;
          }
        }
      `}</style>

      {/* ─── DEDICATED PRINT DOCUMENT (PORTRAIT A4) ─── */}
      <div className="audit-detail-print-only" style={{ fontFamily: PP }}>
        {/* A. HOSPITAL / REPORT HEADER */}
        <div className="border-b-2 border-slate-900 pb-3 mb-4">
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-3">
              {logoLoaded && (
                <img
                  src={effectiveLogo}
                  alt=""
                  onError={() => setLogoLoaded(false)}
                  className="w-14 h-14 object-contain rounded"
                />
              )}
              <div>
                <h1 className="text-lg font-bold text-slate-900 tracking-tight leading-none uppercase">
                  {hospitalName}
                </h1>
                <p className="text-[9.5px] text-slate-600 mt-1">
                  {hospitalAddress}
                  {hospitalPhone && ` • Ph: ${hospitalPhone}`}
                  {hospitalEmail && ` • Email: ${hospitalEmail}`}
                  {hospitalGstin && ` • GSTIN: ${hospitalGstin}`}
                </p>
                <p className="text-[9px] text-slate-500 mt-0.5">
                  Hospital Administration Audit Trail • Verification & Forensic Detail Report
                </p>
              </div>
            </div>

            <div className="text-right">
              <div className="inline-block px-2.5 py-1 bg-slate-900 text-white rounded text-[10px] font-bold tracking-wide uppercase">
                AUDIT DETAIL REPORT
              </div>
              <div className="text-[9.5px] text-slate-600 mt-1.5 space-y-0.5">
                <div>
                  <span className="font-semibold text-slate-800">Audit ID: </span>
                  <span className="font-bold text-slate-900 font-mono">{record.id}</span>
                </div>
                <div>
                  <span className="font-semibold text-slate-800">Generated: </span>
                  <span>{new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</span>
                </div>
                <div>
                  <span className="font-semibold text-slate-800">Event Time: </span>
                  <span className="font-mono text-slate-700">{record.timestamp}</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* SECTION 1: AUDIT EVENT SUMMARY */}
        <div className="mb-4 border border-slate-300 rounded p-3 bg-slate-50/50">
          <div className="flex items-center justify-between border-b border-slate-200 pb-1.5 mb-2.5">
            <h2 className="text-[11px] font-bold text-slate-900 uppercase tracking-wider">
              Section 1: Audit Event Summary
            </h2>
            <div className="flex items-center gap-2 text-[9.5px] font-bold">
              <span
                className={`px-2 py-0.5 rounded ${
                  record.severity === "Critical"
                    ? "bg-red-100 text-red-800"
                    : record.severity === "Warning"
                      ? "bg-amber-100 text-amber-800"
                      : "bg-blue-100 text-blue-800"
                }`}
              >
                Severity: {record.severity || "Information"}
              </span>
              <span className="px-2 py-0.5 rounded bg-emerald-100 text-emerald-800">
                Status: {record.status || "Success"}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-2.5 text-[9px] mb-2.5">
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Audit ID / Event ID</span>
              <span className="font-mono font-bold text-slate-900">{record.id}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Category</span>
              <span className="font-semibold text-slate-800">{record.category}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Module</span>
              <span className="font-bold text-slate-900">{record.module}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Screen Name</span>
              <span className="text-slate-700">{record.module} Workspace</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Generated By</span>
              <span className="font-bold text-slate-900">{record.user}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Department</span>
              <span className="text-slate-700">{record.department || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">User Role</span>
              <span className="font-semibold text-slate-800">{record.userRole}</span>
            </div>
            <div className="col-span-2">
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Event Timestamp</span>
              <span className="font-mono font-bold text-slate-900">{record.timestamp}</span>
            </div>
          </div>

          <div className="mb-2">
            <span className="text-slate-500 font-semibold block uppercase text-[8px] mb-0.5">Action Performed</span>
            <div className="p-2 bg-white rounded border border-slate-200 text-slate-900 font-bold text-[10px]">
              {record.action}
            </div>
          </div>

          <div>
            <span className="text-slate-500 font-semibold block uppercase text-[8px] mb-0.5">Full Event Description</span>
            <div className="p-2 bg-white rounded border border-slate-200 text-slate-800 text-[9px] leading-relaxed break-words">
              {record.description}
            </div>
          </div>
        </div>

        {/* SECTION 2: USER INFORMATION */}
        <div className="mb-4 border border-slate-300 rounded p-3 bg-slate-50/50">
          <h2 className="text-[11px] font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1.5 mb-2.5">
            Section 2: User Information
          </h2>
          <div className="grid grid-cols-3 gap-2.5 text-[9px]">
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">User Name</span>
              <span className="font-bold text-slate-900">{record.user}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">User Role</span>
              <span className="font-semibold text-slate-800">{record.userRole}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Department</span>
              <span className="text-slate-700">{record.department || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">User ID / Email</span>
              <span className="text-slate-700 font-mono">{record.userId || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Account Status</span>
              <span className="font-semibold text-slate-800">{record.status}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Last Login</span>
              <span className="font-mono text-slate-700">{record.loginTime || "—"}</span>
            </div>
          </div>
        </div>

        {/* SECTION 3: ACTIVITY INFORMATION */}
        <div className="mb-4 border border-slate-300 rounded p-3 bg-slate-50/50">
          <h2 className="text-[11px] font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1.5 mb-2.5">
            Section 3: Activity Information
          </h2>
          <div className="grid grid-cols-3 gap-2.5 text-[9px]">
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Action Performed</span>
              <span className="font-bold text-slate-900">{record.action}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Module</span>
              <span className="font-bold text-slate-900">{record.module}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Related Record ID</span>
              <span className="font-mono font-bold text-slate-900">{record.recordId || record.id}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">IP Address</span>
              <span className="font-mono text-slate-700">{record.ipAddress || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Device Type</span>
              <span className="text-slate-800">{record.device || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Browser</span>
              <span className="text-slate-800">{record.browser || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Auth Method</span>
              <span className="text-slate-800">{record.authenticationMethod || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Session ID</span>
              <span className="font-mono text-slate-600 break-all">{record.sessionId || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Network</span>
              <span className="text-slate-700">{record.metadata?.network ? String(record.metadata.network) : "—"}</span>
            </div>
          </div>
        </div>

        {/* SECTION 4: AUDIT TIMELINE */}
        <div className="mb-4 border border-slate-300 rounded p-3 bg-slate-50/50">
          <h2 className="text-[11px] font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1.5 mb-2.5">
            Section 4: Audit Timeline
          </h2>
          <div className="space-y-2">
            <div className="p-2 bg-white rounded border border-slate-200 text-[9px]">
              <div className="flex justify-between font-bold text-slate-900 mb-0.5">
                <span>{record.action}</span>
                <span className="font-mono text-slate-500 text-[8.5px]">{record.timestamp}</span>
              </div>
              <p className="text-slate-600">{record.description}</p>
            </div>
            {(record.changes || []).map((change, idx) => (
              <div key={idx} className="p-2 bg-white rounded border border-slate-200 text-[9px]">
                <div className="flex justify-between font-bold text-slate-900 mb-0.5">
                  <span>Changed {change.field}</span>
                  <span className="font-mono text-slate-500 text-[8.5px]">{record.timestamp}</span>
                </div>
                <p className="font-mono text-slate-700">{change.before} → {change.after}</p>
              </div>
            ))}
          </div>
        </div>

        {/* SECTION 5: DATA COMPARISON (CONDITIONAL) */}
        {(record.category === "Data Changes" || record.fieldChanged) && (
          <div className="mb-4 border border-slate-300 rounded p-3 bg-slate-50/50">
            <h2 className="text-[11px] font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1.5 mb-2.5">
              Section 5: Data Comparison (Field Modifications)
            </h2>
            <div className="text-[9px] font-semibold text-slate-700 mb-2">
              Modified Field: <span className="font-bold text-slate-900">{record.fieldChanged || "—"}</span>
            </div>
            <div className="grid grid-cols-2 gap-3 text-[9px]">
              <div className="p-2 bg-red-50/70 border border-red-200 rounded">
                <span className="font-bold text-red-800 block text-[8px] uppercase mb-1">Previous Value (Before)</span>
                <div className="font-mono text-red-950 bg-white p-2 rounded border border-red-100 break-all">
                  {record.oldValue || "N/A"}
                </div>
              </div>
              <div className="p-2 bg-emerald-50/70 border border-emerald-200 rounded">
                <span className="font-bold text-emerald-800 block text-[8px] uppercase mb-1">Updated Value (After)</span>
                <div className="font-mono text-emerald-950 bg-white p-2 rounded border border-emerald-100 break-all">
                  {record.newValue || "N/A"}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* SECTION 6: RELATED RECORDS */}
        <div className="mb-4 border border-slate-300 rounded p-3 bg-slate-50/50">
          <h2 className="text-[11px] font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1.5 mb-2.5">
            Section 6: Related Records
          </h2>
          <div className="grid grid-cols-2 gap-2 text-[9px]">
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Related Record ID</span>
              <span className="font-mono font-bold text-slate-900">{record.recordId || record.id}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Related Module</span>
              <span className="font-bold text-slate-900">{record.module}</span>
            </div>
          </div>
        </div>

        {/* SECTION 7: TECHNICAL INFORMATION */}
        <div className="mb-4 border border-slate-300 rounded p-3 bg-slate-50/50">
          <h2 className="text-[11px] font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1.5 mb-2.5">
            Section 7: Technical Information
          </h2>
          <div className="grid grid-cols-4 gap-2.5 text-[9px]">
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">IP Address</span>
              <span className="font-mono text-slate-900">{record.ipAddress || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Operating System</span>
              <span className="text-slate-800">{record.metadata?.operatingSystem ? String(record.metadata.operatingSystem) : "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Device Type</span>
              <span className="text-slate-800">{record.device || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">MAC Address</span>
              <span className="font-mono text-slate-800">{record.metadata?.macAddress ? String(record.metadata.macAddress) : "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Hospital Branch</span>
              <span className="font-semibold text-slate-900">{record.metadata?.branch ? String(record.metadata.branch) : "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Session Duration</span>
              <span className="font-mono text-slate-800">{record.sessionDuration || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Login Method</span>
              <span className="text-slate-800">{record.authenticationMethod || "—"}</span>
            </div>
            <div>
              <span className="text-slate-500 font-semibold block uppercase text-[8px]">Timezone</span>
              <span className="font-mono text-slate-800">{record.metadata?.timezone ? String(record.metadata.timezone) : "—"}</span>
            </div>
          </div>
        </div>

        {/* BOTTOM PANEL: RELATED AUDIT EVENTS */}
        {relatedAuditLogs.length > 0 && (
          <div className="mb-4">
            <h2 className="text-[11px] font-bold text-slate-900 uppercase tracking-wider mb-1 flex items-center justify-between">
              <span>Related Audit Events</span>
              <span className="text-[9px] font-normal text-slate-500">{relatedAuditLogs.length} Records</span>
            </h2>
            <table className="w-full text-left border border-slate-300 text-[9px]">
              <thead>
                <tr className="bg-slate-100 text-slate-800 font-bold border-b border-slate-300">
                  <th className="py-1 px-1.5 border-r border-slate-300">Timestamp</th>
                  <th className="py-1 px-1.5 border-r border-slate-300">Module</th>
                  <th className="py-1 px-1.5 border-r border-slate-300">Action</th>
                  <th className="py-1 px-1.5 border-r border-slate-300">Performed By</th>
                  <th className="py-1 px-1.5 border-r border-slate-300">Severity</th>
                  <th className="py-1 px-1.5">Status</th>
                </tr>
              </thead>
              <tbody>
                {relatedAuditLogs.map((log) => (
                  <tr key={log.id} className="border-b border-slate-200">
                    <td className="py-1 px-1.5 font-mono text-slate-600 border-r border-slate-200">{log.timestamp}</td>
                    <td className="py-1 px-1.5 text-slate-700 border-r border-slate-200">{log.module}</td>
                    <td className="py-1 px-1.5 font-semibold text-slate-900 border-r border-slate-200">{log.action}</td>
                    <td className="py-1 px-1.5 font-bold text-slate-900 border-r border-slate-200">{log.user}</td>
                    <td className="py-1 px-1.5 border-r border-slate-200">{log.severity}</td>
                    <td className="py-1 px-1.5">{log.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* E. PAGE FOOTER */}
        <div className="border-t border-slate-300 pt-2 text-[8.5px] text-slate-500 flex justify-between items-center">
          <span>Safe Hands HMS • Audit & Governance Trail</span>
          <span>Confidential — Internal Administrative Use Only</span>
        </div>
      </div>

      {/* ─── NORMAL SCREEN UI ─── */}
      <div
        className="audit-detail-screen-ui flex-1 overflow-y-auto p-6 space-y-6 bg-[#F1F5F9]"
        style={{ fontFamily: RB }}
      >
        {toastMessage && (
          <div className="fixed bottom-16 right-6 z-50 bg-gray-900 text-white px-4 py-3 rounded-lg shadow-xl flex items-center gap-3 border border-gray-700 text-sm animate-bounce">
            <CheckCircle2 className="w-5 h-5 text-emerald-400" />
            <span>{toastMessage}</span>
          </div>
        )}

        {/* WORKSPACE HEADER */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-3">
              <button
                onClick={onBack}
                className="p-2 rounded-xl bg-gray-100 hover:bg-gray-200 text-gray-700 transition-colors"
                title="Back to Audit Logs"
              >
                <ArrowLeft className="w-5 h-5" />
              </button>
              <div>
                <div className="flex items-center gap-3">
                  <h1
                    className="text-2xl font-bold text-gray-900"
                    style={{ fontFamily: PP }}
                  >
                    Audit Log Details
                  </h1>
                  <span className="px-3 py-1 bg-blue-50 text-blue-900 font-mono font-bold rounded-lg border border-blue-200 text-xs">
                    {record.id}
                  </span>
                </div>
                <p className="text-sm text-gray-500 mt-1">
                  Complete audit trail and event information for administrative
                  verification.
                </p>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap items-center gap-2.5">
            <button
              onClick={handlePrint}
              className="inline-flex items-center gap-2 px-3.5 py-2 text-sm font-semibold text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors shadow-sm cursor-pointer"
            >
              <Printer className="w-4 h-4 text-gray-600" />
              Print
            </button>
            <button
              onClick={handleExportPdf}
              className="inline-flex items-center gap-2 px-3.5 py-2 text-sm font-semibold text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors shadow-sm cursor-pointer"
            >
              <FileText className="w-4 h-4 text-red-600" />
              Export PDF
            </button>
            <button
              onClick={() => downloadAuditDetailCsv(record, relatedAuditLogs)}
              className="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white rounded-lg transition-colors shadow-sm cursor-pointer"
              style={{ backgroundColor: "#0D47A1" }}
            >
              <Download className="w-4 h-4" />
              Export CSV
            </button>
          </div>
        </div>

      {/* CONTENT LAYOUT */}
      <div className="space-y-6">
        {/* SECTION 1: AUDIT EVENT SUMMARY */}
        <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-gray-100 pb-3">
            <div className="flex items-center gap-2">
              <Activity className="w-5 h-5 text-blue-700" />
              <h2
                className="text-base font-bold text-gray-900"
                style={{ fontFamily: PP }}
              >
                Section 1: Audit Event Summary
              </h2>
            </div>
            <div className="flex items-center gap-2">
              <SeverityBadgeLarge severity={record.severity} />
              <StatusBadgeLarge status={record.status} />
            </div>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 text-xs bg-gray-50 p-4 rounded-xl border border-gray-200">
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Audit ID
              </span>
              <span className="font-mono font-bold text-gray-900 text-xs mt-0.5 block">
                {record.id}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Event ID
              </span>
              <span className="font-mono font-bold text-blue-900 text-xs mt-0.5 block">
                {record.id}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Category
              </span>
              <span className="font-semibold text-gray-800 text-xs mt-0.5 block">
                {record.category}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Module
              </span>
              <span className="font-bold text-blue-900 text-xs mt-0.5 block">
                {record.module}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Screen Name
              </span>
              <span className="font-medium text-gray-700 text-xs mt-0.5 block">
                {record.module} Workspace
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Timestamp
              </span>
              <span className="font-mono font-bold text-gray-900 text-xs mt-0.5 block">
                {record.timestamp}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Generated By
              </span>
              <span className="font-bold text-gray-900 text-xs mt-0.5 block">
                {record.user}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Department
              </span>
              <span className="font-medium text-gray-700 text-xs mt-0.5 block">
                {record.department}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                User Role
              </span>
              <span className="font-semibold text-gray-800 text-xs mt-0.5 block">
                {record.userRole}
              </span>
            </div>
          </div>
          <div>
            <span className="text-gray-400 text-[10px] uppercase font-bold block mb-1">
              Action Performed
            </span>
            <div className="p-3 bg-blue-50 text-blue-950 font-bold rounded-xl border border-blue-100 text-sm">
              {record.action}
            </div>
          </div>
          <div>
            <span className="text-gray-400 text-[10px] uppercase font-bold block mb-1">
              Full Event Description
            </span>
            <p className="p-3.5 bg-gray-50 text-gray-800 text-xs rounded-xl leading-relaxed border border-gray-200">
              {record.description}
            </p>
          </div>
        </div>

        {/* SECTION 2: USER INFORMATION */}
        <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
          <div className="flex items-center gap-2 border-b border-gray-100 pb-3">
            <User className="w-5 h-5 text-teal-700" />
            <h2
              className="text-base font-bold text-gray-900"
              style={{ fontFamily: PP }}
            >
              Section 2: User Information
            </h2>
          </div>
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 p-4 bg-slate-50 rounded-xl border border-gray-200">
            <div className="w-14 h-14 rounded-full bg-blue-900 text-white font-bold flex items-center justify-center text-lg border-2 border-blue-200 shadow-sm">
              {(record.user || "?")
                .split(" ")
                .map((n) => n[0])
                .join("")
                .slice(0, 2)}
            </div>
            <div className="flex-1 space-y-1 text-xs">
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-bold text-gray-900">
                  {record.user}
                </h3>
                <span className="px-2 py-0.5 bg-blue-100 text-blue-900 rounded font-semibold text-[11px]">
                  {record.userRole}
                </span>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 text-gray-600 pt-1">
                <span className="flex items-center gap-1">
                  <Building2 className="w-3.5 h-3.5 text-gray-400" />
                  {record.department}
                </span>
                <span className="flex items-center gap-1">
                  <Mail className="w-3.5 h-3.5 text-gray-400" />
                  {record.userId || "—"}
                </span>
                <span className="flex items-center gap-1">
                  <Phone className="w-3.5 h-3.5 text-gray-400" />—
                </span>
              </div>
            </div>
            <div className="text-right text-xs">
              <span className="px-2.5 py-1 bg-emerald-100 text-emerald-800 font-bold rounded-full text-[11px] block">
                Status: {record.status}
              </span>
              <span className="text-[11px] text-gray-400 mt-1 block">
                Last Login: {record.loginTime || "—"}
              </span>
            </div>
          </div>
        </div>

        {/* SECTION 3: ACTIVITY INFORMATION */}
        <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
          <div className="flex items-center gap-2 border-b border-gray-100 pb-3">
            <Layers className="w-5 h-5 text-purple-700" />
            <h2
              className="text-base font-bold text-gray-900"
              style={{ fontFamily: PP }}
            >
              Section 3: Activity Information
            </h2>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 text-xs bg-gray-50 p-4 rounded-xl border border-gray-200">
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Action Performed
              </span>
              <span className="font-bold text-gray-900 text-xs mt-0.5 block">
                {record.action}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Module
              </span>
              <span className="font-bold text-blue-900 text-xs mt-0.5 block">
                {record.module}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Related Record ID
              </span>
              <span className="font-mono font-bold text-purple-700 text-xs mt-0.5 block">
                {record.recordId || record.id}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                IP Address
              </span>
              <span className="font-mono text-gray-700 text-xs mt-0.5 block">
                {record.ipAddress}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Device Type
              </span>
              <span className="font-medium text-gray-800 text-xs mt-0.5 block">
                {record.device}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Browser
              </span>
              <span className="font-medium text-gray-800 text-xs mt-0.5 block">
                {record.browser}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Auth Method
              </span>
              <span className="font-semibold text-emerald-700 text-xs mt-0.5 block">
                {record.authenticationMethod || "—"}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Session ID
              </span>
              <span className="font-mono text-gray-600 text-[11px] mt-0.5 block truncate">
                {record.sessionId || "—"}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Network
              </span>
              <span className="font-medium text-gray-700 text-xs mt-0.5 block">
                {record.metadata?.network
                  ? String(record.metadata.network)
                  : "—"}
              </span>
            </div>
          </div>
        </div>

        {/* SECTION 4: AUDIT TIMELINE */}
        <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
          <div className="flex items-center gap-2 border-b border-gray-100 pb-3">
            <Clock className="w-5 h-5 text-indigo-700" />
            <h2
              className="text-base font-bold text-gray-900"
              style={{ fontFamily: PP }}
            >
              Section 4: Audit Timeline
            </h2>
          </div>
          <div className="relative pl-6 space-y-6 before:absolute before:left-2.5 before:top-2 before:bottom-2 before:w-0.5 before:bg-gray-200">
            {[
              {
                title: record.action,
                time: record.timestamp,
                desc: record.description,
              },
              ...(record.changes || []).map((change) => ({
                title: `Changed ${change.field}`,
                time: record.timestamp,
                desc: `${change.before} → ${change.after}`,
              })),
            ].map((step) => (
              <div
                key={step.title}
                className="relative flex items-start gap-4 text-xs"
              >
                <div className="absolute -left-6 top-0.5 w-5 h-5 rounded-full bg-blue-700 text-white flex items-center justify-center text-[10px] font-bold ring-4 ring-white">
                  <Check className="w-3 h-3" />
                </div>
                <div className="flex-1 bg-gray-50 p-3 rounded-xl border border-gray-200">
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-bold text-gray-900">
                      {step.title}
                    </span>
                    <span className="font-mono text-gray-400 text-[11px]">
                      {step.time}
                    </span>
                  </div>
                  <p className="text-gray-600 text-xs">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* SECTION 5: DATA COMPARISON (CONDITIONAL) */}
        {record.category === "Data Changes" && record.fieldChanged && (
          <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
            <div className="flex items-center gap-2 border-b border-gray-100 pb-3">
              <Database className="w-5 h-5 text-teal-700" />
              <h2
                className="text-base font-bold text-gray-900"
                style={{ fontFamily: PP }}
              >
                Section 5: Data Comparison (Field Modifications)
              </h2>
            </div>
            <div className="space-y-3">
              <div className="text-xs font-semibold text-gray-700">
                Modified Field:{" "}
                <span className="font-bold text-blue-900">
                  {record.fieldChanged}
                </span>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="p-4 bg-red-50 rounded-xl border border-red-200">
                  <span className="text-xs font-bold text-red-700 block mb-1">
                    Previous Value (Before)
                  </span>
                  <div className="font-mono text-xs text-red-900 font-bold bg-white p-3 rounded-lg border border-red-200">
                    {record.oldValue || "N/A"}
                  </div>
                </div>
                <div className="p-4 bg-emerald-50 rounded-xl border border-emerald-200">
                  <span className="text-xs font-bold text-emerald-700 block mb-1">
                    Updated Value (After)
                  </span>
                  <div className="font-mono text-xs text-emerald-900 font-bold bg-white p-3 rounded-lg border border-emerald-200">
                    {record.newValue || "N/A"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* SECTION 6: RELATED RECORDS */}
        <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
          <div className="flex items-center gap-2 border-b border-gray-100 pb-3">
            <ExternalLink className="w-5 h-5 text-blue-700" />
            <h2
              className="text-base font-bold text-gray-900"
              style={{ fontFamily: PP }}
            >
              Section 6: Related Records
            </h2>
          </div>
          <div className="flex flex-wrap gap-2">
            {[
              {
                label: `Record: ${record.recordId || record.id}`,
                type: "Record",
              },
              { label: `Module: ${record.module}`, type: "Module" },
            ].map((chip) => (
              <button
                key={chip.label}
                onClick={() => showToast(`Navigating to ${chip.label}...`)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-900 font-semibold text-xs rounded-xl border border-blue-200 transition-colors"
              >
                <span>{chip.label}</span>
                <ExternalLink className="w-3 h-3 text-blue-600" />
              </button>
            ))}
          </div>
        </div>

        {/* SECTION 7: TECHNICAL INFORMATION */}
        <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
          <div className="flex items-center gap-2 border-b border-gray-100 pb-3">
            <Server className="w-5 h-5 text-gray-700" />
            <h2
              className="text-base font-bold text-gray-900"
              style={{ fontFamily: PP }}
            >
              Section 7: Technical Information
            </h2>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs bg-gray-50 p-4 rounded-xl border border-gray-200">
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                IP Address
              </span>
              <span className="font-mono font-bold text-gray-900 text-xs mt-0.5 block">
                {record.ipAddress}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Operating System
              </span>
              <span className="font-medium text-gray-800 text-xs mt-0.5 block">
                {record.metadata?.operatingSystem
                  ? String(record.metadata.operatingSystem)
                  : "—"}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Device Type
              </span>
              <span className="font-medium text-gray-800 text-xs mt-0.5 block">
                {record.device}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                MAC Address
              </span>
              <span className="font-mono text-gray-600 text-xs mt-0.5 block">
                {record.metadata?.macAddress
                  ? String(record.metadata.macAddress)
                  : "—"}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Hospital Branch
              </span>
              <span className="font-semibold text-blue-900 text-xs mt-0.5 block">
                {record.metadata?.branch
                  ? String(record.metadata.branch)
                  : "—"}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Session Duration
              </span>
              <span className="font-mono text-gray-700 text-xs mt-0.5 block">
                {record.sessionDuration || "—"}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Login Method
              </span>
              <span className="font-semibold text-emerald-700 text-xs mt-0.5 block">
                {record.authenticationMethod || "—"}
              </span>
            </div>
            <div>
              <span className="text-gray-400 text-[10px] uppercase font-bold block">
                Timezone
              </span>
              <span className="font-mono text-gray-600 text-xs mt-0.5 block">
                {record.metadata?.timezone
                  ? String(record.metadata.timezone)
                  : "—"}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* BOTTOM PANEL: RELATED AUDIT EVENTS */}
      <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
        <div className="flex items-center justify-between border-b border-gray-100 pb-3">
          <div>
            <h3
              className="text-base font-bold text-gray-900"
              style={{ fontFamily: PP }}
            >
              Bottom Panel: Related Audit Events
            </h3>
            <p className="text-xs text-gray-500 mt-0.5">
              Latest related audit records from the system log stream.
            </p>
          </div>
          <span className="text-xs font-bold text-blue-900 bg-blue-50 px-3 py-1 rounded-full border border-blue-200">
            {relatedAuditLogs.length} Related Records
          </span>
        </div>
        <div className="overflow-x-auto rounded-xl border border-gray-200">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-200 text-gray-600 font-bold uppercase tracking-wider">
                <th className="p-3.5">Timestamp</th>
                <th className="p-3.5">Module</th>
                <th className="p-3.5">Action</th>
                <th className="p-3.5">Performed By</th>
                <th className="p-3.5">Severity</th>
                <th className="p-3.5">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200 bg-white font-medium text-gray-800">
              {relatedAuditLogs.map((log) => (
                <tr
                  key={log.id}
                  className="hover:bg-blue-50/40 transition-colors"
                >
                  <td className="p-3.5 font-mono text-gray-500">
                    {log.timestamp}
                  </td>
                  <td className="p-3.5">
                    <span className="px-2 py-0.5 rounded bg-gray-100 font-medium text-gray-700">
                      {log.module}
                    </span>
                  </td>
                  <td className="p-3.5 font-semibold text-blue-950">
                    {log.action}
                  </td>
                  <td className="p-3.5 font-bold text-gray-900">{log.user}</td>
                  <td className="p-3.5">
                    <SeverityBadgeLarge severity={log.severity} />
                  </td>
                  <td className="p-3.5">
                    <StatusBadgeLarge status={log.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      </div>
    </>
  );
}
